scripts:
  - name: Clean Flutter
    script: |
      flutter clean
      rm -rf ios/Pods
      rm -rf ios/Podfile.lock
      rm -rf ios/.symlinks
      flutter pub get

  - name: Install CocoaPods
    script: |
      cd ios
      pod repo update
      pod install
      cd ..

  - name: Build iOS
    script: |
      flutter build ipa --release
