// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhAumxZHdo9F6f7kI9ynv-e_3T4qyoU5s',
    appId: '1:911354788511:web:c7844152929d1b44b000aa',
    messagingSenderId: '911354788511',
    projectId: 'domina-rep',
    authDomain: 'domina-rep.firebaseapp.com',
    storageBucket: 'domina-rep.firebasestorage.app',
    measurementId: 'G-01NV4XK09Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_d-2szpbuditQEjuhpeIxa7Wji_ETXgE',
    appId: '1:911354788511:android:777af6398a3f5604b000aa',
    messagingSenderId: '911354788511',
    projectId: 'domina-rep',
    storageBucket: 'domina-rep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAENCcMN6_pugBF_CXYfGMxVn7FKkF7VA',
    appId: '1:911354788511:ios:2dd11ee37324920db000aa',
    messagingSenderId: '911354788511',
    projectId: 'domina-rep',
    storageBucket: 'domina-rep.firebasestorage.app',
    iosBundleId: 'com.example.dominaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAENCcMN6_pugBF_CXYfGMxVn7FKkF7VA',
    appId: '1:911354788511:ios:2dd11ee37324920db000aa',
    messagingSenderId: '911354788511',
    projectId: 'domina-rep',
    storageBucket: 'domina-rep.firebasestorage.app',
    iosBundleId: 'com.example.dominaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhAumxZHdo9F6f7kI9ynv-e_3T4qyoU5s',
    appId: '1:911354788511:web:8f4f30b56ace16bfb000aa',
    messagingSenderId: '911354788511',
    projectId: 'domina-rep',
    authDomain: 'domina-rep.firebaseapp.com',
    storageBucket: 'domina-rep.firebasestorage.app',
    measurementId: 'G-K798R812QE',
  );
}
