name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_CHANNEL: stable

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.6' # يمكنك تعديل الإصدار حسب مشروعك (أو استبدال السطر بـ channel: 'stable' لاستخدام أحدث إصدار)
          cache: true # تفعيل التخزين المؤقت لتسريع عملية البناء

      - name: Get dependencies
        run: flutter pub get

      - name: Check formatting
        run: |
          dart format --output=none --set-exit-if-changed . || {
            echo "Some files are not formatted."
            echo "Run: dart format ."
            exit 0
          }
      # ✅ 2. التحقق من سلامة الكود والتحذيرات
      - name: Flutter analyze
        run: flutter analyze

      # ✅ 3. تشغيل الـ Build Runner (تم التحديث للأمر الحديث dart run)
      - name: Run codegen
        run: dart run build_runner build --delete-conflicting-outputs

      # ✅ 4. تشغيل الاختبارات واستخراج التغطية (Coverage)
      - name: Run tests
        run: flutter test --coverage

      # ✅ 5. بناء تطبيق APK عند الدمج في الفرع الرئيسي فقط
      - name: Build APK (optional)
        if: github.ref == 'refs/heads/main'
        run: flutter build apk --release

      # ✅ 6. رفع تقرير التغطية
      - name: Upload coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/lcov.info
